package com.Pearl;

public enum Suits {
    HEART, DIAMOND, CLUB , SPADE , HEARTJACK ,DIAMONDJACK, CLUBJACK, SPADEJACK,
    HEARTQUEEN ,DIAMONDQUEEN, CLUBQUEEN, SPADEQUEEN,
    HEARTKING ,DIAMONDKING, CLUBKING, SPADEKING
}
